// angular/src/app/gantt.controls.component.ts
import {Component, Input} from "@angular/core"
import {GanttService} from "./gantt.service"

@Component({
  selector:"jtk-gantt-controls",
  template:`<div class="jtk-gantt-controls">
    <button (click)="resetView()">HOME</button>
    <button (click)="addTask()">NEW TASK</button>
    <button (click)="addTaskGroup()">NEW TASK GROUP</button>
    <button (click)="addMilestone()">NEW MILESTONE</button>
    <button (click)="exportToConsole()">EXPORT TO CONSOLE</button>
  </div>
    
  `
})
export class GanttControlsComponent {

  @Input() chartId!:string

  constructor(private service:GanttService) { }

  resetView() {
    this.service.resetView(this.chartId)
  }

  addTask() {
    this.service.addNewTask(this.chartId)
  }

  addMilestone() {
    this.service.addNewMilestone(this.chartId)
  }

  addTaskGroup() {
    this.service.addNewTaskGroup(this.chartId)
  }

  exportToConsole() {
    this.service.exportToConsole(this.chartId)
  }
}

// react/src/GanttControls.tsx
import {Gantt} from "./defs"
import {useContext} from "react"
import {GanttContext} from "./GanttProvider"
import {addNewMilestone, addNewTask, addNewTaskGroup} from "./util"

export default function GanttControls() {

    let {listen} = useContext(GanttContext)

    function resetView() {
        listen((g:Gantt) => {
            g.zoomToFit()
        })
    }

    function addTask() {
        listen((g:Gantt) => {
            addNewTask(g)
        })
    }

    function addTaskGroup() {
        listen((g:Gantt) => {
            addNewTaskGroup(g)
        })
    }

    function addMilestone() {
        listen((g:Gantt) => {
            addNewMilestone(g)
        })
    }

    function exportToConsole() {
        listen((g:Gantt) => {
            g.exportToConsole()
        })
    }

    return <div className="jtk-gantt-controls">
        <button onClick={() => resetView()}>HOME</button>
    <button onClick={() => addTask()}>NEW TASK</button>
    <button onClick={() => addTaskGroup()}>NEW TASK GROUP</button>
    <button onClick={() => addMilestone()}>NEW MILESTONE</button>
    <button onClick={() => exportToConsole()}>EXPORT TO CONSOLE</button>
    </div>
}
