// angular/src/app/gantt.inspector.ts
import {AfterViewInit, Component, Input, OnInit} from "@angular/core"
import {Surface } from "@jsplumbtoolkit/browser-ui"
import {InspectorComponent} from "@jsplumbtoolkit/browser-ui-angular"

@Component({
  template: `<div class="inspector">
    
        @if(currentType === 'task') {
          <div class="jtk-gantt-inspector jtk-task-inspector">
            
              <div>Name</div>
              <input type="text" jtk-att="name" jtk-focus/>
              <div>Progress</div>
              <div style="display:flex;align-items:center">
                <input type="range" jtk-att="progress" min="0" max="100" value="{{currentObj.data.progress}}" (input)="updateRangeLabel($event)"/>
                <div class="jtk-gantt-progress-value-label">{{currentObj.data.progress}}</div>
              </div>
          </div>
        }

        @if(currentType === 'taskGroup') {
          <div class="jtk-gantt-inspector jtk-task-group-inspector">
            <div>Name</div>
            <input type="text" jtk-att="name" jtk-focus/>
          </div>
        }  

        @if(currentType === 'milestone') {
          <div class="jtk-gantt-inspector jtk-task-milestone-inspector">
            <div>Name</div>
            <input type="text" jtk-att="name" jtk-focus/>
          </div>
        }  
    
    </div>`,
  selector: 'jtk-gantt-inspector'
})
export class GanttInspector extends InspectorComponent implements OnInit {

  @Input() chartId!:string

  ngOnInit() {
    this.surfaceId = this.chartId
  }

  // updates the label next to the range slider for a task.
  updateRangeLabel(e:Event) {
    const el = e.target as HTMLInputElement
    const newValue = el.value
    el.nextElementSibling && (el.nextElementSibling.innerHTML = `${newValue}`)
  }

  /**
   * We relayout after an update because that causes the decoration to be repainted.
   */
  override afterUpdate(surface:Surface) {
    surface.relayout()
  }


}

// react/src/GanttInspector.tsx
import {InspectorComponent} from "@jsplumbtoolkit/browser-ui-react"
import {Base, Node, Surface} from "@jsplumbtoolkit/browser-ui"
import {useContext, useState} from "react"
import {TYPE_TASK} from "./constants"
import {GanttContext} from "./GanttProvider"

export default function GanttInspector() {

    const {listen } = useContext(GanttContext)

    const [currentObj, setCurrentObj] = useState<Node>(null)
    const [currentType, setCurrentType] = useState('')

    const [progress,setProgress] = useState(0)

    const renderEmptyContainer = () => setCurrentType('')
    const refresh = (obj:Base) => {
        setCurrentType(obj.type)
        setCurrentObj(obj as Node)
        setProgress(obj.data.progress || 0)
    }

    function updateRangeLabel(e:Event) {
        setProgress((e as any).target.value)
    }

    function afterUpdate(surface:Surface) {
        surface.relayout()
    }

    return <InspectorComponent className="jtk-gantt-inspector"
                               refresh={refresh}
                               renderEmptyContainer={renderEmptyContainer}
                                showCloseButton={true}
                                afterUpdate={afterUpdate}>

        {currentType === TYPE_TASK && <div className="jtk-gantt-inspector jtk-task-inspector">
            <div>Name</div>
            <input type="text" jtk-att="name" jtk-focus="true"/>
            <div>Progress</div>
            <div style={{display:"flex",alignItems:"center"}}>
                <input type="range" jtk-att="progress" min="0" max="100" defaultValue={currentObj.data.progress} onInput={(e) => updateRangeLabel(e)}/>
                <div className="jtk-gantt-progress-value-label">{progress}</div>
            </div>
            </div>}

    </InspectorComponent>
}
