// angular/src/app/task.group.component.ts
import {Component} from "@angular/core"
import {BAR_HEIGHT} from "../constants"
import {GanttService} from "./gantt.service"
import {BaseGanttTaskComponent} from "./base.task.component"

@Component({
  template:`<div class="jtk-gantt-task-group" data-jtk-target="true" style="left:{{obj.left}}px;width:{{obj.size}}px;height:${BAR_HEIGHT}px;background-color:{{obj.color}}" jtk-y-resize="false" jtk-x-resize="false" data-jtk-not-draggable="true">
                <div class="jtk-gantt-delete" (click)="deleteMe()">×</div>
                <div class="jtk-gantt-connect" data-jtk-source="true">+</div>
            </div>`
})
export class TaskGroupComponent extends BaseGanttTaskComponent {

  constructor(service:GanttService) {
    super(service)
  }

}

// react/src/components/TaskGroupComponent.tsx
import {BAR_HEIGHT} from "../../../angular/src/constants"

export default function TaskGroupComponent({ctx, removeTask}) {

    const { vertex, data } = ctx

    return <div className="jtk-gantt-task-group" data-jtk-target="true" style={{left:`${data.left}px`,width:`${data.size}px`,height:`${BAR_HEIGHT}px`, backgroundColor:data.color}} jtk-y-resize="false" jtk-x-resize="false" data-jtk-not-draggable="true">
            <div className="jtk-gantt-delete" onClick={() => removeTask(vertex.id)}>×</div>
            <div className="jtk-gantt-connect" data-jtk-source="true">+</div>
        </div>

}
