// angular/src/app/task.component.ts
import { BaseNodeComponent } from "@jsplumbtoolkit/browser-ui-angular"
import {Component} from "@angular/core"
import {BAR_HEIGHT} from "../constants"
import {GanttService} from "./gantt.service"
import {BaseGanttTaskComponent} from "./base.task.component"

@Component({
  template:`<div class="jtk-gantt-task" data-jtk-target="true" style="left:{{obj.left}}px;width:{{obj.size}}px;height:${BAR_HEIGHT}px;background-color:{{obj.color}}" jtk-y-resize="false" [attr.data-jtk-show-progress]="showProgress">                
                <div class="jtk-gantt-progress-value">{{obj.progress}}</div>
                <div class="jtk-gantt-progress-gauge" style="width:{{obj.progress}}%"></div>
                <div class="jtk-gantt-delete" (click)="deleteMe()">×</div>
                <div class="jtk-gantt-connect" data-jtk-source="true">+</div>                
            </div>`
})
export class TaskComponent extends BaseGanttTaskComponent {

  showProgress = true

  constructor(service:GanttService) {
    super(service)
  }


  // deleteTask() {
  //   this.service.removeNode(this.getNode())
  // }

}

// react/src/components/TaskComponent.tsx
import {BAR_HEIGHT} from "../../../angular/src/constants"

export default function TaskComponent({ctx, showProgress,  removeTask}) {

    const { vertex, data } = ctx


    return <div className="jtk-gantt-task" data-jtk-target="true" style={{left:`${data.left}px`,width:`${data.size}px`, height:`${BAR_HEIGHT}px`, backgroundColor:`${data.color}`}} jtk-y-resize="false" data-jtk-show-progress={showProgress}>
                <div className="jtk-gantt-progress-value">{data.progress}</div>
                <div className="jtk-gantt-progress-gauge" style={{width:`${data.progress}%`}}/>
                <div className="jtk-gantt-delete" onClick={() => removeTask(vertex.id)}>×</div>
                <div className="jtk-gantt-connect" data-jtk-source="true">+</div>
            </div>

}
